### PR TITLE
Issue68

### PR DESCRIPTION
**Pull request by greenTara**

### CODE REVIEW

**Comment by lisp** [comment]
i may be lagging behind in notifications, but

```
rsp-mm -> rsp
```

?

**Comment by greenTara** [comment]
I have responded to the comment above and made the change in the namespace and prefix. Would a reviewer please check and merge (or comment) on this pull request now?

**Comment by jpcik** [comment]
seems to me that the terminology and prefix changes are alright

**Comment by greenTara** [comment]
The merge of this pull request closes issue #68

**Pull request merged**
