### PR TITLE
implementing Define isomorphism of RDF stream relative to sequence order

### PR DESCRIPTION
**Pull request by greenTara**

### CODE REVIEW

**Comment by greenTara** [comment]
Daniele - would you please review this pull request? Thanks!

**Comment by dellaglio** [comment]
The definitions are clear, but I have only one concern: can an RDF stream be infinite?
If yes, the isomorphism on RDF streams is semi-decidable, as it is possible to state that two streams are not isomorphic, but not that they are isomprhic.

If what I wrote above is right, I would suggest to add a "practical" notion of isomorphism. That means, isomorphism on a window content (that is limited), or "isomorphism between streams up to time x".

**Comment by greenTara** [comment]
Yes, since an RDF stream is defined as a sequence, it can be either finite or infinite. The definition doesn't exclude it, so I suppose it could even be bi-infinite.
Note that this is also true for RDF graphs (and datasets). An RDF graph is defined as a set of triples. There is no requirement that it be finite.

There is another section of the document that defines window functions (see https://github.com/streamreasoning/RSP-QL/pull/42). In some cases, the output of the window function will be finite. In those cases, the determination of isomorphism of the resulting streams is decidable. But just specifying a cutoff time is not enough to guarantee finiteness (e.g. Zeno's paradox).

I would be interested to see what practical kinds of isomorphism are needed.

**Comment by dellaglio** [comment]
Right, I was (wrongly) assuming that the time is defined in N. 
Thank you for the clarification

**Comment by jpcik** [comment]
#31

**Comment by greenTara** [comment]
@dellaglio , @jpcik  Can we merge this pull request now? I think the only outstanding question is a "practical" notion of isomorphism, and I think that is outside the scope of the original issue.

**Comment by dellaglio** [comment]
Yes, we can merge it.

Il Gio 3 Mar 2016 00:08 Tara Athan notifications@github.com ha scritto:

> @dellaglio https://github.com/dellaglio , @jpcik
> https://github.com/jpcik Can we merge this pull request now? I think
> the only outstanding question is a "practical" notion of isomorphism, and I
> think that is outside the scope of the original issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/streamreasoning/RSP-QL/pull/37#issuecomment-191502851
> .
> 
> ## 

## 

Sent from my Android phone. Please excuse my brevity.

**Comment by greenTara** [comment]
close #31

**Pull request merged**
