### PR TITLE
Ticket 25: Defined temporal concept, added owl-Time as an example

### PR DESCRIPTION
**Pull request by beortner**

### CODE REVIEW

**Comment by beta2k** [comment]
#25

**Comment by greenTara** [comment]
The requirement introduced here that all timestamps are time instants is not consistent with the definition of timestamped graph, where "timestamp" is the role that is played by the temporal entity that is the subject of the timestamp triple, and is not required to be a time instant.

I don't think it is necessary to define, or use, the term "timestamp" in this section - it is formally defined in the definition of a timestamped graph.

**Comment by greenTara** [comment]
The case has not been made for the added specifications, either from the Requirements document or on technical grounds. There are perfectly good, usable temporal ontologies that have no time instants at all. There are temporal ontologies of branching time, that have a quite different topology than OWL TIME. I agree that OWL TIME is worth mentioning as an example, because it is a W3C recommendation and is fairly intuitive. As such, it should be marked up as an example:

```
    <aside class="example highlight" title="OWL TIME"> ...
```

**Comment by greenTara** [comment]
The Respec user guide https://www.w3.org/respec/guide.html contains useful information regarding references. https://www.w3.org/respec/guide.html#references OWL TIME can be referenced as

```
[[OWL-TIME]]
```

Also, please use the Editor's note feature

```
<p class="ednote">...
```

rather than XML comments for e.g. the reference to an issue.

**Comment by greenTara** [comment]
The pull request should be into gh-pages, not the master branch. It appears that the master branch was used as the parent for this commit, which is behind the gh-pages branch by several commits. Would you please transfer to the correct file (index.html in gh-pages) and create a new pull request?

**Comment by beortner** [comment]
Please close this branch, I have added a new one (25.2) for the ticket.

**Comment by greenTara** [comment]
Replaced by #58

**Pull request closed without merging**
